# Generated by Django 2.2.3 on 2020-03-16 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_remove_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_id', models.CharField(max_length=10, verbose_name='考试编号')),
                ('exam_type', models.CharField(max_length=128, verbose_name='考试类别')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
                ('exam_time', models.CharField(max_length=128, verbose_name='考试时间')),
                ('number', models.IntegerField(verbose_name='容量')),
                ('entry_number', models.IntegerField(default=0, verbose_name='已报名数量')),
            ],
            options={
                'verbose_name': '考点',
                'verbose_name_plural': '考点信息表',
            },
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('user_true_name', models.CharField(max_length=128, null=True, verbose_name='真实姓名')),
                ('user_id', models.CharField(max_length=18, null=True, verbose_name='身份证号')),
                ('user_school', models.CharField(max_length=128, verbose_name='在读学校')),
                ('user_f_score', models.IntegerField(default=0, verbose_name='四级成绩')),
                ('user_s_score', models.IntegerField(default=0, verbose_name='六级成绩')),
            ],
            options={
                'verbose_name': '用户名',
                'verbose_name_plural': '用户信息表',
            },
        ),
        migrations.CreateModel(
            name='user_entry_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('exam_id', models.CharField(max_length=10, verbose_name='考试编号')),
                ('exam_point', models.CharField(max_length=128, verbose_name='考点')),
            ],
            options={
                'verbose_name': '用户考试信息',
                'verbose_name_plural': '用户考试信息表',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=20, verbose_name='姓名')),
                ('idCard', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('phone1', models.CharField(max_length=20, verbose_name='联系电话1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话2')),
                ('primarySchool', models.CharField(blank=True, max_length=50, null=True, verbose_name='毕业小学')),
                ('juniorSchool', models.CharField(max_length=50, verbose_name='毕业初中')),
                ('testScore1', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='初三上学期期中考成绩')),
                ('testRank1', models.IntegerField(blank=True, null=True, verbose_name='初三上学期期中考年级排名')),
                ('testScore2', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='初三上学期期末考成绩')),
                ('testRank2', models.IntegerField(blank=True, null=True, verbose_name='初三上学期期末考年级排名')),
                ('specialty', models.CharField(blank=True, max_length=200, null=True, verbose_name='特长')),
                ('photo', models.ImageField(upload_to='image', verbose_name='照片')),
                ('c_time', models.DateTimeField(auto_now_add=True)),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='用户名')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['c_time'],
            },
        ),
    ]
