# Generated by Django 2.2.3 on 2020-03-16 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classRoom', models.CharField(max_length=50, verbose_name='试室号')),
                ('seatNo', models.CharField(max_length=20, verbose_name='座位号')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.Student')),
            ],
            options={
                'verbose_name': '准考证',
                'verbose_name_plural': '准考证',
            },
        ),
    ]
