# Generated by Django 2.0.1 on 2020-03-17 02:21

from django.db import migrations
import home.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_certification'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='zip_file',
            field=home.fields.RestrictedFileField(blank=True, null=True, upload_to='', verbose_name='证明文件'),
        ),
    ]
